Enable ip_tables kernel module on startup
In Almalinux 9 ip_tables kernel module is not enabled by default. If
they can't be loaded (probably because iptables-services is missing as a
package) sysbox will throw an error.

Signed-off-by: Christos Roussidis <xristos.roussidis@gmail.com>

diff --git a/scr/sysbox b/scr/sysbox
--- a/scr/sysbox
+++ b/scr/sysbox
@@ -61,6 +61,11 @@ function load_required_modules() {
       echo "Could not load configfs kernel module. Exiting ..."
       return 1
 	fi
+        if ! modprobe ip_tables &> /dev/null; then
+      echo "Could not load ip_tables kernel module. Exiting ..."
+      return 1
+        fi
+
 
 	return 0
 }
