Re-work testContainerInit script to leverage the new docker-cfg script.
Signed-off-by: Cesar Talledo <ctalledo@nestybox.com>

diff --git a/tests/scr/testContainerInit b/tests/scr/testContainerInit
--- a/tests/scr/testContainerInit
+++ b/tests/scr/testContainerInit
@@ -1,13 +1,14 @@
-#!/bin/bash -e
+#!/bin/bash
 
 #
 # Test container initialization script
 #
 
-
 # Dockerd default configuration dir/file.
 dockerCfgDir="/etc/docker"
 dockerCfgFile="${dockerCfgDir}/daemon.json"
+
+dockerd=$(which dockerd)
 
 # Default mtu value associated to test-container's egress-interface.
 default_mtu=1500
@@ -16,7 +17,8 @@ default_mtu=1500
 tmpfile=$(mktemp /tmp/init-scr.XXXXXX)
 trap 'rm -f "${tmpfile}"' EXIT
 
-
+# Retries the given command a given number of attempts, each after a given delay
+# (e.g., retry 10 1 <command>)
 function retry() {
   local attempts=$1
   shift
@@ -24,19 +26,16 @@ function retry() {
   shift
   local i
 
-  set +e
   for ((i = 0; i < attempts; i++)); do
-    $@
+    $@ > /dev/null 2>&1
     if [ "$?" -eq 0 ]; then
-      set -e
       return 0
     fi
     sleep $delay
   done
 
-  set -e
   echo "Command \"$@\" failed $attempts times. Output: $?"
-  false
+  return 1
 }
 
 #
@@ -56,7 +55,7 @@ function docker_iface_mtu() {
     # Identify default egress iface.
     local egress_iface=$(ip route show | awk '/default via/ {print $5}')
     if [ -z "${egress_iface}" ]; then
-	return
+		 return
     fi
 
     # Obtain mtu value associated to the test-container's egress interface.
@@ -78,10 +77,45 @@ function docker_iface_mtu() {
     fi
 }
 
+# Adjust the test container's Docker mtu configuration. This is required to
+# avoid forwarding issues in containers seating behind an egress-interface with
+# lower-than-default mtu.
+function docker_config_mtu() {
+	egress_mtu=$(docker_iface_mtu)
+	if [ ! -z "${egress_mtu}" ] && [ "${egress_mtu}" -ne "${default_mtu}" ]; then
+		jq --arg mtu "${egress_mtu}" --indent 4 '. + {"mtu": $mtu|tonumber}' "${dockerCfgFile}" \
+			> ${tmpfile} && cp ${tmpfile} "${dockerCfgFile}"
+	fi
+}
 
 #
 # Execution starts here ...
 #
+
+# Install helper scripts
+install -D -m0755 scr/sysbox /usr/local/sbin/sysbox
+install -D -m0755 scr/docker-cfg /usr/local/sbin/docker-cfg
+
+# Start the test container's Docker daemon
+$dockerd > /var/log/dockerd.log 2>&1 &
+retry 10 1 docker ps
+[ $? -eq 0 ] || exit 1
+
+# Configure Docker to use Sysbox (leveraging the docker-cfg script)
+common_opt="-v --config-only --sysbox-runtime=enable --skip-network-config --default-runtime=sysbox-runc"
+
+if [ -z "$SHIFT_UIDS" ]; then
+	docker-cfg $common_opt --userns-remap=enable
+	[ $? -eq 0 ] || exit 1
+else
+	docker-cfg $common_opt
+	[ $? -eq 0 ] || exit 1
+fi
+
+docker_config_mtu
+
+# Restart Docker after MTU config
+docker-cfg --force-restart --skip-network-config
 
 # Build & install sysbox
 thisHost=$(hostname)
@@ -97,72 +131,8 @@ if [[ "$lastBuildHost" != "$thisHost" ]]; then
   make clean
 fi
 
-# Configure dockerd
-mkdir -p "${dockerCfgDir}"
-
-if [ -z "$SHIFT_UIDS" ]; then
-    cat <<EOF > "${dockerCfgFile}"
-{
-    "debug": false,
-    "userns-remap": "sysbox",
-    "runtimes": {
-        "sysbox-runc": {
-            "path": "/usr/local/sbin/sysbox-runc"
-        }
-    },
-    "default-runtime": "sysbox-runc",
-    "bip": "172.24.0.1/16",
-    "default-address-pools": [
-        {
-            "base": "172.31.0.0/16",
-            "size": 24
-        }
-    ]
-}
-EOF
-else
-    cat <<EOF > "${dockerCfgFile}"
-{
-    "debug": false,
-    "userns-remap": "",
-    "runtimes": {
-        "sysbox-runc": {
-            "path": "/usr/local/sbin/sysbox-runc",
-            "runtimeArgs": [
-                "--no-kernel-check"
-            ]
-        }
-    },
-    "default-runtime": "sysbox-runc",
-    "bip": "172.24.0.1/16",
-    "default-address-pools": [
-        {
-            "base": "172.31.0.0/16",
-            "size": 24
-        }
-    ]
-}
-EOF
-fi
-
-# Adjust docker's interface mtu configuration. This is required to avoid forwarding issues
-# in containers seating behind an egress-interface with lower-than-default mtu.
-egress_mtu=$(docker_iface_mtu)
-if [ ! -z "${egress_mtu}" ] && [ "${egress_mtu}" -ne "${default_mtu}" ]; then
-    jq --arg mtu "${egress_mtu}" --indent 4 '. + {"mtu": $mtu|tonumber}' "${dockerCfgFile}" \
-       > ${tmpfile} && cp ${tmpfile} "${dockerCfgFile}"
-fi
-
-# Start docker
-dockerd > /var/log/dockerd.log 2>&1 &
-retry 10 0.5 docker ps > /dev/null 2>&1
-
 # Build sysbox suite.
 make sysbox-local --no-print-directory && make install
 
-# Inside the test container we start sysbox with a dedicated script
-# that sets some test-specific configs
-echo "Starting sysbox with test-specific options"
-install -D -m0755 scr/sysbox /usr/local/sbin/sysbox
-sysbox testing-on
-
+echo "Starting sysbox in test mode"
+sysbox -t
