Adjust building framework to accomodate CentOS distribution

diff --git a/tests/scr/testContainerPre b/tests/scr/testContainerPre
--- a/tests/scr/testContainerPre
+++ b/tests/scr/testContainerPre
@@ -8,10 +8,11 @@ TEST_VOL3=$3
 # can't be checked from within the test container since its docker
 # image may be based on another distro)
 
-DISTRO=$(lsb_release -i | awk '{print $3}')
-if [ "$DISTRO" != "Ubuntu" ]; then
-  printf "\nError: sysbox uid shifting is only supported on Ubuntu hosts.\n\n"
-  exit 1
+DISTRO=$(lsb_release -is)
+
+if [ "$DISTRO" != "Ubuntu" ] && [ "$DISTRO" != "CentOS" ]; then
+    printf "\nError: sysbox is not supported in this distribution: %s.\n\n", $DISTRO
+    exit 1
 fi
 
 # See Makefile for description of test volumes
