Fixed indentation in testSysboxCI script.
Signed-off-by: Cesar Talledo <ctalledo@nestybox.com>

diff --git a/tests/scr/testSysboxCI b/tests/scr/testSysboxCI
--- a/tests/scr/testSysboxCI
+++ b/tests/scr/testSysboxCI
@@ -8,44 +8,46 @@ progName=$(basename "$0")
 
 usage()
 {
-  echo "
+	echo "
 Usage: $progName <testName>
 
 "
-  exit 1
+	exit 1
 }
 
 # argument testName is optional
 if [ $# -eq 1 ]; then
-  printf "\nExecuting $1 ... \n"
-  bats --tap $1
+	printf "\nExecuting $1 ... \n"
+	bats --tap $1
 else
-  printf "\nExecuting sysbox-mgr tests ... \n"
-  bats --tap tests/sysmgr
-  printf "\nExecuting sysbox-fs tests ... \n"
-  bats --tap tests/sysfs
-  printf "\nExecuting docker tests ... \n"
-  bats --tap tests/docker
-  printf "\nExecuting dind tests ... \n"
-  bats --tap tests/dind
-  printf "\nExecuting cind tests ... \n"
-  bats --tap tests/cind
-  printf "\nExecuting app tests (l1) ... \n"
-  bats --tap tests/apps/l1
+	printf "\nExecuting sysbox-mgr tests ... \n"
+	bats --tap tests/sysmgr
+	printf "\nExecuting sysbox-fs tests ... \n"
+	bats --tap tests/sysfs
+	printf "\nExecuting syscall tests ... \n"
+	bats --tap tests/syscall
+	printf "\nExecuting docker tests ... \n"
+	bats --tap tests/docker
+	printf "\nExecuting dind tests ... \n"
+	bats --tap tests/dind
+	printf "\nExecuting cind tests ... \n"
+	bats --tap tests/cind
+	printf "\nExecuting app tests (l1) ... \n"
+	bats --tap tests/apps/l1
 
-  # the kind tests need plenty storage (otherwise kubelet fails);
-  # remove all docker images from prior tests to make room, and
-  # remove all docker images after test too.
-  printf "\n"
-  docker system prune -a -f
-  printf "\nExecuting kind tests ... \n"
-  bats --tap tests/kind/kindbox-custom-net.bats
-  docker system prune -a -f
+	# the kind tests need plenty storage (otherwise kubelet fails);
+	# remove all docker images from prior tests to make room, and
+	# remove all docker images after test too.
+	printf "\n"
+	docker system prune -a -f
+	printf "\nExecuting kind tests ... \n"
+	bats --tap tests/kind/kindbox-custom-net.bats
+	docker system prune -a -f
 
-  printf "\nSysbox health checking ...\n"
-  bats --tap tests/health/sysbox-health.bats
+	printf "\nSysbox health checking ...\n"
+	bats --tap tests/health/sysbox-health.bats
 
-  docker system prune -a -f
+	docker system prune -a -f
 fi
 
 exit 0
