Verify that sysvisor tests with shiftfs are executed on a supported distro.

diff --git a/tests/scr/testContainerPre b/tests/scr/testContainerPre
--- a/tests/scr/testContainerPre
+++ b/tests/scr/testContainerPre
@@ -3,6 +3,18 @@
 TEST_VOL1=$1
 TEST_VOL2=$2
 
+# if using shiftfs, check that the host meets sysvisor-runc distro
+# requirements (this can be checked from within the test container
+# since its docker image may be based from another distro)
+
+if [ -n $SHIFT_UIDS ]; then
+  DISTRO=$(lsb_release -i | awk '{print $3}')
+  if [ $DISTRO != "Ubuntu" ]; then
+    printf "\nError: Sysvisor uid shifting is only supported on Ubuntu hosts.\n\n"
+    exit 1
+  fi
+fi
+
 # See Makefile for description of test volumes
 mkdir -p $TEST_VOL1
 mkdir -p $TEST_VOL2
